MODEL:
  MODEL_NAME : "HypVinn"
  NUM_CLASSES : 27
  NUM_CHANNELS : 14
  LOSS_FUNC: "combined"
  KERNEL_H: 3
  KERNEL_W: 3
  BASE_RES: 1.0
  NUM_FILTERS_INTERPOL : 64
  NUM_FILTERS : 80
  OUT_TENSOR_WIDTH: 320
  OUT_TENSOR_HEIGHT: 320
  HEIGHT: 256
  WIDTH: 256
  MODE : 'multi'
  MULTI_AUTO_W : True
  HETERO_INPUT : True

DATA:
  SIZES : [320]
  PATH_HDF5_TRAIN : '/data/train_data_08mm/split5/train_split5_axial.hdf5'
  PATH_HDF5_VAL : ''
  PLANE : 'axial'
  AUG: ['Scaling','Gaussian','Rotation','Translation','BiasField']
  PADDED_SIZE : 320
  REF_FRAME : -1
  VAL_REF_FRAME : 0

TRAIN :
  BATCH_SIZE : 16
  NUM_EPOCHS : 100
  RUN_VAL : FALSE

OPTIMIZER:
  OPTIMIZING_METHOD : 'adamW'
  WEIGHT_DECAY : 1e-4
  BASE_LR : 0.05
  GAMMA: 0.1
  LR_SCHEDULER : 'multiStep'
  MILESTONES: [70]
  MOMENTUM : 0.95

NUM_GPUS : 2
LOG_DIR : "/src/FSVINN/hetero_models/split5" 