MODEL:
  MODEL_NAME: "FastSurferVINN"
  LOSS_FUNC: "combined"
  NUM_FILTERS: 71
  NUM_FILTERS_INTERPOL: 32
  NUM_CHANNELS: 7
  NUM_CLASSES: 3
  KERNEL_H: 3
  KERNEL_W: 3
  KERNEL_C: 1
  STRIDE_CONV: 1
  STRIDE_POOL: 2
  POOL: 2
  HEIGHT: 256
  WIDTH: 256
  BASE_RES: 1.0
  INTERPOLATION_MODE: "bilinear"
  CROP_POSITION: "top_left"
  OUT_TENSOR_WIDTH: 429
  OUT_TENSOR_HEIGHT: 429

TRAIN:
  LOG_INTERVAL: 50
  RESUME: false
  RESUME_EXPR_NUM: "Default"
  NUM_STEPS: 10
  FINE_TUNE: false
  CHECKPOINT_PERIOD: 4
  NUM_EPOCHS: 2000
  BATCH_SIZE: 32
  DEBUG: false

TEST:
  BATCH_SIZE: 16

DATA:
  SIZES: None
  PADDED_SIZE: [429, 9, 7] # [axis1, axis2, thickness]
  PLANE: "axial"
  PATH_HDF5_TRAIN: "/data/cropped-nocom-loc/axial_train.hdf5"
  PATH_HDF5_VAL: "/data/cropped-nocom-loc/axial_val.hdf5"
  AUG: [] # "Hemisphere" "Flip"
  LUT: "/home/CCNet/config/CC_ColorLUT_nocom.tsv"
  #AUG_LIKELYHOOD: [0.8, 0.4] # Gaussian does not support probability

DATA_LOADER:
  NUM_WORKERS: 0
  PIN_MEMORY: true
  #PREFETCH_FACTOR: 3

OPTIMIZER:
  BASE_LR: 0.01
  LR_SCHEDULER: "cosineWarmRestarts"
  GAMMA: 0.3
  STEP_SIZE: 5
  ETA_MIN: 0.0001
  T_ZERO: 10
  T_MULT: 2
  MOMENTUM: 0.9
  DAMPENING: 0.0
  NESTEROV: true
  WEIGHT_DECAY: 0.0001
  OPTIMIZING_METHOD: "adamW"

NUM_GPUS: 4
#INPAINT_LOSS_WEIGHT: 0.5  # Weight of intensity image in loss function
RNG_SEED: 1
LOG_DIR: "/home/experiments/cc_axial_pad/"
#LOG_LEVEL: 10
EXPR_NUM: "cc_axial_pad_02"
