## Start with ubuntu base

FROM ubuntu:20.04
ENV LANG=C.UTF-8
ARG PYTHON_VERSION=3.8
ENV DEBIAN_FRONTEND=noninteractive

# Install custom libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
         wget \
         git \
         ca-certificates && \
         rm -rf /var/lib/apt/lists/*

# Install miniconda and needed python packages (for FastSurferCNN)
RUN wget -qO ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-py37_4.10.3-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda install -y python=$PYTHON_VERSION python-dateutil=2.8.2 pyyaml=6.0 matplotlib=3.5.1 h5py=3.6.0 scikit-image=0.19.2 && \
     /opt/conda/bin/conda install -y cpuonly pytorch=1.10.0 torchvision=0.11.1 cudatoolkit=11.3 -c pytorch && \
     /opt/conda/bin/conda install -y -c conda-forge pillow=9.0.1 && \
     /opt/conda/bin/conda clean -ya
ENV PYTHONUNBUFFERED=0 \
    PATH=/opt/conda/bin:$PATH

# install pip related dependencies
RUN python$PYTHON_VERSION -m pip install -U git+https://github.com/Deep-MI/LaPy.git#egg=lapy && \
    python$PYTHON_VERSION -m pip install numpy==1.22.3 && \
    python$PYTHON_VERSION -m pip install scipy==1.8.0 && \
    python$PYTHON_VERSION -m pip install nibabel==3.2.2

# Add FastSurfer (copy application code) to docker image
COPY ./FastSurferCNN /FastSurferCNN/
COPY ./checkpoints /FastSurferCNN/checkpoints/
WORKDIR "/FastSurferCNN"

ENTRYPOINT ["python3.6", "eval.py"]
CMD ["--help"]