## Start with Docker pytorch base

FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu16.04
ENV LANG=C.UTF-8
ARG PYTHON_VERSION=3.6

# Install custom libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
         git \
         wget && \
         rm -rf /var/lib/apt/lists/*
	 
# Install miniconda and needed python packages (for FastSurferCNN)
RUN wget -qO ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-py37_4.10.3-Linux-x86_64.sh  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh && \
     /opt/conda/bin/conda install -y python=$PYTHON_VERSION numpy scipy matplotlib h5py scikit-image && \
     /opt/conda/bin/conda install -y -c pytorch cudatoolkit=10.0 "pytorch=1.2.0=py3.6_cuda10.0.130_cudnn7.6.2_0" torchvision=0.4.0 && \
     /opt/conda/bin/conda install -y -c conda-forge scikit-sparse nibabel=2.5.1 pillow=8.3.2 && \
     /opt/conda/bin/conda clean -ya
ENV PYTHONUNBUFFERED=0 \
    PATH=/opt/conda/bin:$PATH

# install pip related dependencies
RUN python$PYTHON_VERSION -m pip install -U git+https://github.com/Deep-MI/LaPy.git#egg=lapy

# Add FastSurfer (copy application code) to docker image
COPY ./FastSurferCNN /FastSurferCNN/
COPY ./checkpoints /FastSurferCNN/checkpoints/
WORKDIR "/FastSurferCNN"

ENTRYPOINT ["python3.6", "eval.py"]
CMD ["--help"]
