## Start with ubuntu base

FROM ubuntu:20.04 AS build
ENV LANG=C.UTF-8
ARG PYTHON_VERSION=3.8
ARG CONDA_FILE=Miniconda3-py38_4.11.0-Linux-x86_64.sh
ENV DEBIAN_FRONTEND=noninteractive

# get install scripts into docker
COPY ./fastsurfer_env_cpu.yml /fastsurfer/fastsurfer_env_cpu.yml

# Install packages needed for build
RUN apt-get update && apt-get install -y --no-install-recommends \
      wget \
      git \
      ca-certificates \
      upx \
      file && \
    apt clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* 

# Install conda
RUN wget --no-check-certificate -qO ~/miniconda.sh https://repo.continuum.io/miniconda/$CONDA_FILE  && \
     chmod +x ~/miniconda.sh && \
     ~/miniconda.sh -b -p /opt/conda && \
     rm ~/miniconda.sh 

ENV PATH /opt/conda/bin:$PATH

# Install our dependencies
RUN conda env create -f /fastsurfer/fastsurfer_env_cpu.yml 

# Install conda-pack:
RUN conda install -c conda-forge conda-pack

# Use conda-pack to create a standalone enviornment in /venv:
RUN conda-pack -n fastsurfer_cpu -o /tmp/env.tar && \
  mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
  rm /tmp/env.tar

# Now that venv in a new location, fix up paths:
RUN /venv/bin/conda-unpack
ENV PATH /venv/bin:$PATH

# setup shell for install command below
RUN echo "source /venv/bin/activate" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]

# ========================================
# Here we create the smaller runtime image
# ========================================

FROM ubuntu:20.04 AS runtime

# Add venv to path:
ENV PATH=/venv/bin:$PATH

# make sure we use bash and activate conda env
#  (in case someone starts this interactively)
RUN echo "source /venv/bin/activate" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]

# Copy venv and FastSurferCNN 
COPY --from=build /venv /venv
COPY ./FastSurferCNN /fastsurfer/FastSurferCNN/
COPY ./checkpoints /fastsurfer/FastSurferCNN/checkpoints/
COPY ./Docker/entrypoint.sh /fastsurfer/Docker/entrypoint.sh

# Download all remote network checkpoints already
ENV PYTHONPATH=/fastsurfer:$PYTHONPATH \
    MPLCONFIGDIR=/tmp
RUN python3 /fastsurfer/FastSurferCNN/download_checkpoints.py --all; chmod +r -R /fastsurfer/FastSurferCNN/checkpoints

# Set FastSurfer workdir and entrypoint
#  the script entrypoint ensures that our conda env is active
WORKDIR "/fastsurfer"
ENV FASTSURFER_HOME=/fastsurfer
ENTRYPOINT ["./Docker/entrypoint.sh", "python3.8", "./FastSurferCNN/run_prediction.py"]
CMD ["--help"]
