"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import os

from setuptools import setup

build_dir = os.path.dirname(os.path.realpath(__file__))
APP = [build_dir + '/FastSurfer.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    py_modules=[],
)
