#!/bin/bash

# Copyright 2023 Image Analysis Lab, German Center for Neurodegenerative Diseases (DZNE), Bonn
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function usage()
{
cat <<EOF
export_pip-r.sh <requirements file> <docker image/singularity image file>

Will generate a backend-neutral requirements file from docker/singularity images
to distribute with the FastSurfer repository. Backend-specific PyTorch wheel
suffixes, PyTorch index URLs, nvidia-* runtime packages, and triton packages are
intentionally omitted; select those at install/build time with uv --torch-backend.

examples:
export_pip-r.sh $FASTSURFER_HOME/requirements.txt fastsurfer:dev
export_pip-r.sh $FASTSURFER_HOME/requirements.txt fastsurfer.sif

Created 26-11-2023, David Kügler, Image Analysis Lab,
German Center for Neurodegenerative Diseases (DZNE), Bonn
EOF
}

if [ "$#" != 2 ]
then
  echo "This scripts expects 2 parameters, got $#"
  exit 1
fi

echo "Exporting versions from $2..."

target=$1
image=$2
display_target=${EXPORT_PIP_R_DISPLAY_TARGET:-$target}
display_args=("$display_target" "$image")
tmp_target=$(mktemp "${target}.tmp.XXXXXX") || exit 1
trap 'rm -f "$tmp_target"' EXIT

{
  echo "#"
  echo "# This file is autogenerated by $USER from $image"
  echo "# by the following command from FastSurfer:"
  echo "#"
  echo "#    $0 ${display_args[*]}"
  echo "#"
} > "$tmp_target"

pip_cmd="python --version && pip list --format=freeze --no-color --disable-pip-version-check --no-input --no-cache-dir"
if [[ "$image" == *.sif ]]
then
  # singularity
  if command -v singularity > /dev/null
  then
    singularity_cmd=singularity
  elif command -v apptainer > /dev/null
  then
    singularity_cmd=apptainer
  else
    echo "Could not find singularity or apptainer to inspect $image"
    exit 1
  fi
  cmd=("$singularity_cmd" "exec" "$image" "/bin/bash" -c "$pip_cmd")
  clean_cmd="$singularity_cmd exec $image /bin/bash -c '$pip_cmd'"
else
  # docker
  clean_cmd="docker run --rm -u <user_id>:<group_id> --entrypoint /bin/bash $image -c '$pip_cmd'"
  cmd=("docker" "run" --rm -u "$(id -u):$(id -g)" --entrypoint /bin/bash "$image" -c "$pip_cmd")
fi
{
  echo "# Which ran the following command:"
  echo "#    $clean_cmd"
  echo "#"
} >> "$tmp_target"
echo "Running '${cmd[*]}' to get $target"
if ! out=$("${cmd[@]}")
then
  echo "Failed to inspect $image"
  exit 1
fi
hardware=$(echo "$out" | grep "torch==" | cut -d"+" -f2 | tr -d '\n')
pyversion=$(echo "$out" | head -n 1 | cut -d" " -f2)
{
  echo "#"
  echo "# Backend-neutral pinned requirements for FastSurfer."
  echo "#"
  echo "# Image was configured for $hardware using python version $pyversion."
  echo "#"
  echo "# This file pins the shared Python dependency set, but intentionally does not"
  echo "# pin backend-specific PyTorch wheel variants, PyTorch index URLs, nvidia-*"
  echo "# runtime packages, or triton. Select those at install time with uv's"
  echo "# --torch-backend option, for example:"
  echo "#"
  echo "#    uv pip compile --torch-backend=cu128 requirements.txt | uv pip sync --torch-backend=cu128 -"
  echo "#    uv pip compile --torch-backend=cpu requirements.txt | uv pip sync --torch-backend=cpu -"
  echo "#"
  echo "# To refresh this file from a container image, run:"
  echo "#"
  echo "#    $0 ${display_args[*]}"
  echo "#"
  echo "$out" \
    | tail -n +2 \
    | sed -E \
      -e '/^nvidia-/d' \
      -e '/^triton==/d' \
      -e '/^pytorch-triton/d' \
      -e 's/^((torch|torchvision|torchaudio)==[^+[:space:]]+)\+[^[:space:]]+/\1/'
} >> "$tmp_target"

mv "$tmp_target" "$target"
trap - EXIT
