name: Build and release macOS packages

on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-mac:
    runs-on: macos-14
    timeout-minutes: 60
    strategy:
      matrix:
        arch: [intel, arm]
    steps:
      - name: Get repository name.
        run: echo "FASTSURFER_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Set up python environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: install dependencies
        run: |
          python -m venv .venv
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> "$GITHUB_ENV"
          echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"
          . .venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install py2app tomli
          
          # update system to the newest version, not pin pointing package version on purpose
          brew update  
          brew upgrade || true
          brew list aria2 >/dev/null 2>&1 || brew install aria2
      - name: package app for ${{ matrix.arch }}
        run: tools/macos_build/build_release_package.sh ${{ matrix.arch }}
      - name: Move assets.
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          mkdir assets
          mv tools/macos_build/installer/* assets/
      - name: Upload release assets.
        uses: softprops/action-gh-release@v3.0.0
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          files: ${{ env.FASTSURFER_DIR }}/assets/*
