name: MAN release/deploy

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy-mac:
    runs-on: macos-14
    timeout-minutes: 120
    
    env:
      RELEASE_ASSETS: true
    strategy:
      matrix:
        arch: [intel, arm]
    steps:
      - name: Get repository name.
        run: echo "FASTSURFER_DIR=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up python environment
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: install dependencies
        run: |
          python -m pip install py2app tomli
          
          # update system to the newest version, not pin pointing package version on purpose
          brew update  
          brew upgrade || true
          brew install aria2
      - name: package app for ${{ matrix.arch }}
        run: tools/macos_build/build_release_package.sh ${{ matrix.arch }}
      - name: Move assets.
        if: env.RELEASE_ASSETS == 'true'
        run: |
          mkdir assets
          mv tools/macos_build/installer/* assets/
      - name: Upload release assets.
        uses: softprops/action-gh-release@v2
        if: env.RELEASE_ASSETS == 'true'
        with:
          files: ${{ env.FASTSURFER_DIR }}/assets/*

