name: dirac-docker

on:
  # push:
  #   branches: [ "dev" ]
  # pull_request:
  #   branches: [ "dev" ]

  workflow_dispatch:
  

jobs:

  build:
    runs-on: dirac

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    
    - name: Run the Docker image
      run: |
        docker pull deepmi/fastsurfer
        # PYTHONPATH=<FastSurferRoot>
        # python build.py --device cuda --tag my_fastsurfer:cuda
        docker run --gpus all -v /home/user/my_mri_data:/data \
                      -v /home/user/my_fastsurfer_analysis:/output \
                      -v /home/user/my_fs_license_dir:/fs_license \
                      --rm --user $(id -u):$(id -g) my_fastsurfer:cuda \
                      --fs_license /fs_license/license.txt \
                      --t1 /data/subjectX/t1-weighted.nii.gz \
                      --sid subjectX --sd /output \
                      --parallel
