# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: FastSurfer Docker Image Build

on:
  # push:
  #   branches: [ "dev" ]
  # pull_request:
  #   branches: [ "dev" ]
  # Manual
  workflow_dispatch:

jobs:
  build:
    runs-on: dirac

    steps:
    # Checkout repo
    - uses: actions/checkout@v4

    # Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Build GPU FastSurfer Image
      run: |
        PYTHONPATH=$PYTHONPATH
        python3 Docker/build.py --device cuda --tag my_fastsurfer:cuda

        docker run --gpus all -v /home/user/my_mri_data:/data \
                      -v /home/user/my_fastsurfer_analysis:/output \
                      -v /home/user/my_fs_license_dir:/fs_license \
                      --rm --user $(id -u):$(id -g) my_fastsurfer:cuda \
                      --fs_license /fs_license/license.txt \
                      --t1 /data/subjectX/t1-weighted.nii.gz \
                      --sid subjectX --sd /output \
                      --parallel
