name: quicktest-docker

on:
  workflow_dispatch:

jobs:
  # Checkout repo
  checkout:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

  # Prepare job: Set up Python, Go, Singularity
  run-fastsurfer:
    runs-on: self-hosted
    needs: checkout
    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

  # Run pytest
  run-pytest:
      runs-on: self-hosted
      needs: run-fastsurfer
      steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install package
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install --progress-bar off .[test]
      - name : Run pytest
        run: pytest test/quicktest
