name: Run Tests

on:
  # push:
  #   branches: [ "dev" ]
  # pull_request:
  #   branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ci-gpu

    steps:
    # Checkout repo
    - uses: actions/checkout@v4

    # Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pyyaml
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  # Test file existence
  test-file-existence:
    runs-on: ci-gpu
    needs: build
    
    steps:    
    - name: Test File Existence
      run: |
        python3 test/test_file_existence.py $RUNNER_FS_OUTPUT_FILES

  # Test for errors in log files
  test-error-messages:
    runs-on: ci-gpu
    needs: test-file-existence
    
    steps:    
    - name: Test Log Files For Error Messages
      run: |
        python3 test/test_error_messages.py $RUNNER_FS_OUTPUT_LOGS
