name: Run Tests

on:
  # push:
  #   branches: [ "dev" ]
  # pull_request:
  #   branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: dirac

    steps:
    # Checkout repo
    - uses: actions/checkout@v4

    # Set up Python 3.10
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install pyyaml
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  test-file-existence:
    runs-on: dirac
    needs: build
    
    steps:
    - name: Test File Existence
      run: |
        python3 -m unittest test.test_file_existence

  test-error-messages:
    runs-on: dirac
    needs: build
    
    steps:
    - name: Test Error Messages
      run: |
        python3 -m unittest test.test_error_messages
